const wordDictionary = [
  { word: "serendipity", meaning: "the occurrence of events by chance in a happy or beneficial way" },
  { word: "ephemeral", meaning: "lasting for a very short time" },
  { word: "luminescence", meaning: "light produced without heat" },
  { word: "sonder", meaning: "realization that others have a life as complex as your own" },
  { word: "mellifluous", meaning: "sweet or musical sound" },
  { word: "petrichor", meaning: "pleasant smell after rain" },
  { word: "zenith", meaning: "the highest point" },
  { word: "solitude", meaning: "the state of being alone" },
  { word: "eloquent", meaning: "fluent or persuasive in speaking or writing" },
  { word: "tranquil", meaning: "free from disturbance; calm" },
  { word: "ineffable", meaning: "too great or extreme to be expressed in words" },
  { word: "limerence", meaning: "the state of being infatuated with another person" },
  { word: "ethereal", meaning: "extremely delicate and light" },
  { word: "sonder", meaning: "realization everyone has their own story" },
  { word: "halcyon", meaning: "denoting a period of time that was idyllically happy" },
  { word: "labyrinth", meaning: "a complicated irregular network of passages" },
  { word: "sonder", meaning: "the realization that each passerby has a life as vivid and complex as your own" },
  { word: "reverie", meaning: "a state of being pleasantly lost in one's thoughts" },
  { word: "silhouette", meaning: "the dark shape of someone or something visible against a lighter background" },
  { word: "epiphany", meaning: "a sudden realization or insight" },
  { word: "sonder", meaning: "everyone has a story just as complex as yours" },
  { word: "solace", meaning: "comfort in a time of distress" },
  { word: "quintessential", meaning: "representing the most perfect example" },
  { word: "elixir", meaning: "a magical or medicinal potion" },
  { word: "panacea", meaning: "a solution for all difficulties or diseases" },
  { word: "euphoria", meaning: "a feeling of intense happiness" },
  { word: "aurora", meaning: "natural light display in the sky" },
  { word: "cascade", meaning: "a small waterfall" },
  { word: "zen", meaning: "a state of calm attentiveness" },
  { word: "bucolic", meaning: "relating to the pleasant aspects of countryside" },
  { word: "sonder", meaning: "the realization that others have lives as vivid and complex as your own" },
  { word: "ephemeral", meaning: "short-lived, lasting a very short time" },
  { word: "resilience", meaning: "capacity to recover quickly from difficulties" },
  { word: "eloquence", meaning: "fluent or persuasive speaking or writing" },
  { word: "luminous", meaning: "bright or shining" },
  { word: "wanderlust", meaning: "a strong desire to travel" },
  { word: "idyllic", meaning: "extremely happy and peaceful" },
  { word: "elegy", meaning: "a poem of serious reflection, typically a lament for the dead" },
  { word: "effervescent", meaning: "vivacious and enthusiastic" },
  { word: "rendezvous", meaning: "a meeting at an agreed time and place" },
  { word: "epitome", meaning: "a perfect example" },
  { word: "muse", meaning: "a source of inspiration" },
  { word: "ambrosial", meaning: "exceptionally pleasing to taste or smell" },
  { word: "cynosure", meaning: "a person or thing that is the center of attention" },
  { word: "vellichor", meaning: "the strange wistfulness of used bookstores" },
  { word: "inevitable", meaning: "certain to happen" },
  { word: "lullaby", meaning: "a song sung to send a child to sleep" },
  { word: "eloquent", meaning: "clearly expressing or indicating something" },
  { word: "gossamer", meaning: "something light, delicate, or insubstantial" },
  { word: "sonder", meaning: "deep awareness that everyone has a complex story" }
];

export const gerarPalavras = (quantidade = 5) => {
  const embaralhadas = [...wordDictionary].sort(() => Math.random() - 0.5);
  return embaralhadas.slice(0, quantidade);
};
